bank_app/urls.py
from django.urls import path, include
from . import views
from channels.routing import ProtocolTypeRouter, URLRouter, ChannelNameRouter
from .api import UserProfileDetail, UserProfileList, AccountsList, AccountsPerTypeList, TransactionsList, TransactionsPerAccountList


app_name = 'bank_app'

urlpatterns = [
    path('bank/view_accounts/', views.view_accounts, name='view_accounts'),
    path('bank/view_users/', views.view_users, name='view_users'),
    path('bank/view_users/<str:user_id>',
         views.user_details, name='user_details'),
    path('bank/create_user/', views.create_user, name='create_user'),
    path('bank/create_account/', views.create_account, name='create_account'),
    path('bank/user_types/', views.user_types, name='user_types'),
    path('bank/view_account_details/<str:account_id>',
         views.view_account_details, name='view_account_details'),
    path('bank/send_notification/',
         views.send_notification, name='send_notification'),
    path('bank/access_denied/', views.access_denied, name='access_denied'),
    path('bank/generate_pdf_with_account_details/<str:account_id>',
         views.generate_pdf_with_account_details, name='generate_pdf_with_account_details'),
    path('customer/view_profile/', views.view_profile, name='view_profile'),
    path('customer/user_view_account_details/<int:account_id>',
         views.user_view_account_details, name='user_view_account_details'),
    path('customer/form_make_loan_payment/', views.form_make_loan_payment,
         name='form_make_loan_payment'),
    path('customer/view_my_accounts/',
         views.view_my_accounts, name='view_my_accounts'),
    path('customer/form_take_a_loan/',
         views.form_take_a_loan, name='form_take_a_loan'),
    path('customer/form_transfer_money/', views.form_transfer_money,
         name='form_transfer_money'),
    path('customer/access_denied/', views.access_denied, name='access_denied'),
    path('api/v1/accounts/', AccountsList.as_view({'get': 'list'})),
    path('api/v1/accounts/<str:account_type>/',
         AccountsPerTypeList.as_view({'get': 'list'})),
    #path('api/v1/accounts/<int:account_id>/', AccountsList.as_view({'get':'retrieve'})),
    path('api/v1/transactions/', TransactionsList.as_view({'get': 'list'})),
    path('api/v1/transactions/<int:account_number>/',
         TransactionsPerAccountList.as_view({'get': 'list'})),
    path('api/v1/customers/<int:user_id>/',
         UserProfileDetail.as_view({'get': 'retrieve'})),
    path('api/v1/customers/<str:user_type_text>/',
         UserProfileList.as_view({'get': 'retrieve'})),
    path('api/v1/rest-auth/', include('rest_auth.urls')),

]

bank_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('bank_app/', include('bank_app.urls')),
    path('accounts/', include('login_app.urls')),
]

login_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views



app_name = 'login_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('password_reset_secret/<str:secret>',
         views.password_reset_secret, name='password_reset_secret'),
    path('password_reset_form/', views.password_reset_form,
         name='password_reset_form'),
    path('password_change/', views.password_change, name='password_change'),

    
]

bank_app/views.py
from django.contrib.auth.models import Group
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Account, Transaction, User, UserType, UserProfile
from django.db.models import Sum, F
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
import django_rq
from . generate_pdf import generatePDF
import uuid
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync
from decimal import Decimal
from django.core.exceptions import ValidationError


def view_users(request):
    users = User.objects.filter(groups__name='Clients')
    context = {
        'users': users
    }
    return render(request, 'bank_app/view_users.html', context)


def user_details(request, user_id):
    user = get_object_or_404(User, id=user_id)
    user_profile = get_object_or_404(UserProfile, user=user)
    phone_number = user_profile.phone_number
    user_rank = user_profile.user_type.text
    bankAcccounts = user_profile.accounts
    context = {
        'user_details': user,
        'bank_accounts': bankAcccounts,
        'phone_number': phone_number,
        'user_rank': user_rank
    }

    return render(request, 'bank_app/view_details.html', context)


def view_accounts(request):
    bankAcccounts = Account.objects.annotate(
        ammount=Sum('transaction__ammount'))
    context = {
        'bankAcccounts': bankAcccounts
    }
    return render(request, 'bank_app/view_accounts.html', context)


def create_user(request):
    userTypes = UserType.objects.all()
    context = {
        "user_types": userTypes
    }
    if request.method == "POST":
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        user_name = request.POST['user_name']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        phone_number = request.POST['phone_number']
        email = request.POST['email']
        type_id = request.POST['type']
        user_type = UserType.objects.get(id=type_id)
        if password == confirm_password:
            userProfile = UserProfile()
            userProfile.create_user_profile(
                user_name, first_name, last_name, email, password, user_type, phone_number)

            messages.success(request, 'User created successfully!')
            return HttpResponseRedirect(reverse('bank_app:view_users'))

        else:
            messages.warning(
                request, 'Passwords did not match. Please try again.')
            context = {
                'error': 'Passwords did not match. Please try again.'
            }
    return render(request, 'bank_app/create_user.html', context)


def create_account(request):
    if request.method == "POST":
        initial_ammount = request.POST['initial_ammount']
        user_id = request.POST['name_user_id']
        user = get_object_or_404(User, id=user_id)
        bank_acccount = Account()
        bank_acccount.create_bank_account(user, initial_ammount)
        messages.success(request, 'Account was successfully created!')
        return HttpResponseRedirect(f'../view_users/{user_id}')
    return render(request, 'bank_app/user_details.html')


def user_types(request):
    if request.method == "POST":
        userType = UserType()
        loan_permission = request.POST['loan_permission']
        user_type = request.POST['user_type']
        userType.create_user_type(loan_permission, user_type)
        messages.success(request, 'Successfully added new user type!')
        return HttpResponseRedirect(f'../user_types')
    userType = UserType.objects.all()
    context = {
        'userType': userType,
    }
    return render(request, 'bank_app/user_types.html', context)


def view_account_details(request, account_id):
    account = get_object_or_404(Account, id=account_id)
    accountTransactions = Transaction.objects.select_related().filter(
        account_id=str(account_id))
    context = {
        'account': account,
        'accountTransactions': accountTransactions
    }

    return render(request, 'bank_app/view_account_details.html', context)


def send_notification(request):
    if request.method == "POST":
        message = request.POST['message']

        messages.success(request, 'Notfication was successfully sent!')
        channel_layer = get_channel_layer()
        # Pass any data based on your requirement
        data = message
        # Trigger message sent to group
        async_to_sync(channel_layer.group_send)(
            "notifications",  # Group Name, Should always be string
            {
                "type": "notify",   # Custom Function written in the consumers.py
                "text": data,
            },
        )
        return render(request, 'bank_app/send_notification.html')

    return render(request, 'bank_app/send_notification.html')


def access_denied(request):
    return render(request, 'bank_app/access_denied.html')


def generate_pdf_with_account_details(request, account_id):

    pdf_id = uuid.uuid4()
    source_html = 'bank_app/pdf-tmpl.html'
    output_filename = 'pdf/' + str(pdf_id) + '.pdf'

    django_rq.enqueue(generatePDF, source_html,
                      output_filename, account_id)

    return HttpResponseRedirect(reverse('bank_app:view_account_details', args=[account_id]))


def form_make_loan_payment(request):
    accounts = Account.objects.filter(
        user_id=request.user, account_type="standard")
    loans = Account.objects.filter(user_id=request.user, account_type="loan")
    context = {
        'accounts': accounts,
        'loans': loans
    }

    if request.method == "POST":
        standard_account_number = request.POST['standard_account_number']
        loan_account_number = request.POST['loan_account_number']
        amount = request.POST['amount']
        standard_account = get_object_or_404(
            Account, account_number=standard_account_number)
        loan_account = get_object_or_404(
            Account, account_number=loan_account_number)
        try:
            transaction = Transaction()
            transaction.transfer(
                standard_account, loan_account, "loan payment", Decimal(amount), is_loan=False)
            messages.success(request, "Loan payment successful.")
            return HttpResponseRedirect(reverse('bank_app:view_my_accounts'))
        except ValidationError as err:
            messages.warning(
                request, err.messages)
            return render(request, 'bank_app/form_make_loan_payment.html', context)
    else:
        return render(request, 'bank_app/form_make_loan_payment.html', context)


def form_take_a_loan(request):

    accounts = Account.objects.filter(
        user_id=request.user, account_type="standard")

    context = {
        'accounts': accounts
    }

    if request.method == "POST":
        try:
            number_account_to = request.POST['account']
            amount = request.POST['amount']
            account_to = get_object_or_404(
                Account, account_number=number_account_to)
            request.user.userprofile.take_loan(account_to, amount)
            messages.success(request, "Successfully added a new loan.")
            return HttpResponseRedirect(reverse('bank_app:view_my_accounts'))
        except ValidationError as err:
            messages.warning(
                request, err.messages)
            return render(request, 'bank_app/form_take_a_loan.html', context)
    else:
        return render(request, 'bank_app/form_take_a_loan.html', context)


def form_transfer_money(request):
    accounts = Account.objects.filter(
        user_id=request.user, account_type="standard")
    context = {
        'accounts': accounts
    }

    if request.method == "POST":
        standard_account_number = request.POST['standard_account_number']
        receiver_account_number = request.POST['receiver_account_number']
        bank_code = request.POST['bank_code']
        standard_account = get_object_or_404(
            Account, account_number=standard_account_number)
        if(bank_code == "10"):
            print("internal")
            receiver_account = get_object_or_404(
                Account, account_number=receiver_account_number)
        else:
            print("external")
            receiver_account = get_object_or_404(
                Account, account_number=28694578)
            externalAccountNumber = receiver_account_number

        description = request.POST['description']
        amount = request.POST['amount']
        try:
            transaction = Transaction()
            transaction.transfer(
                standard_account, receiver_account, description, Decimal(amount), externalAccountNumber, bank_code, is_loan=False)
            messages.success(request, "Transfer successful.")
            channel_layer = get_channel_layer()
            # Pass any data based on your requirement
            data = "You have just received money from " + standard_account.user_id.username
            # Trigger message sent to group
            print(receiver_account.user_id.pk)
            async_to_sync(channel_layer.group_send)(
                # Group Name, Should always be string
                str(receiver_account.user_id.pk),
                {
                    "type": "notifyAboutTransfer",
                    "text": data,
                },
            )
            return HttpResponseRedirect(reverse('bank_app:view_my_accounts'))
        except ValidationError as err:
            messages.warning(
                request, err.messages)
            return render(request, 'bank_app/form_transfer_money.html', context)

    else:
        return render(request, 'bank_app/form_transfer_money.html', context)


def user_view_account_details(request, account_id):

bank_app/templates/bank_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
		/>
		<meta http-equiv="X-UA-Compatible" content="ie=edge" />
		<!-- Bootstrap CSS -->
		<link
			rel="stylesheet"
			href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
			integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
			crossorigin="anonymous"
		/>
		<link
			rel="stylesheet"
			type="text/css"
			href="{% static 'bank_app/style.css' %}"
		/>

		<title>Bank</title>
	</head>
	<body>
		<header class="site-header">
			<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
				<div class="container">
					<p class="navbar-brand mr-4">Bank home</p>
					<button
						class="navbar-toggler"
						type="button"
						data-toggle="collapse"
						data-target="#navbarToggle"
						aria-controls="navbarToggle"
						aria-expanded="false"
						aria-label="Toggle navigation"
					>
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarToggle">
						<div class="navbar-nav mr-auto">
							<a
								class="nav-item nav-link {% block nav_users%}{% endblock %}"
								href="{% url 'bank_app:view_users' %}"
								>Users</a
							>
							<a
								class="nav-item nav-link {% block nav_accounts%}{% endblock %}"
								href="{% url 'bank_app:view_accounts' %}"
								>Accounts</a
							>
							<a
								class="nav-item nav-link {% block nav_ranks%}{% endblock %}"
								href="{% url 'bank_app:user_types' %}"
								>User ranks</a
							>
							<a
								class="nav-item nav-link {% block nav_notification%}{% endblock %}"
								href="{% url 'bank_app:send_notification' %}"
								>Send notification</a
							>
						</div>
						<!-- Navbar Right Side -->
						<div class="navbar-nav">
							<a class="nav-item nav-link" href="{% url 'login_app:logout' %}"
								>Log out ({{ user.username}} )
							</a>
						</div>
					</div>
				</div>
			</nav>
		</header>

		<main role="main" class="container">
			<div class="row">
				<!-- message alerts -->
				{% for message in messages %}
				<div class="container-fluid p-0">
					<div class="alert {{ message.tags }} alert-dismissible" role="alert">
						<button
							type="button"
							class="close"
							data-dismiss="alert"
							aria-label="Close"
						>
							<span aria-hidden="true">&times;</span>
						</button>
						{{ message }}
					</div>
				</div>
				{% endfor %}

				<div class="col-md-12">{% block content %} {% endblock %}</div>
			</div>
		</main>

		{% block footer %} {% endblock %}

		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script
			src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
			integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
			crossorigin="anonymous"
		></script>
		<script
			src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
			integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
			crossorigin="anonymous"
		></script>
		<script
			src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
			integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
			crossorigin="anonymous"
		></script>
	</body>
</html>

bank_app/templates/bank_app/base_customer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
		/>
		<meta http-equiv="X-UA-Compatible" content="ie=edge" />
		<!-- Bootstrap CSS -->
		<link
			rel="stylesheet"
			href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
			integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
			crossorigin="anonymous"
		/>
		<link
			rel="stylesheet"
			type="text/css"
			href="{% static 'bank_app/style.css' %}"
		/>

		<title>Bank</title>
	</head>
	<body>
		<header class="site-header">
			<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
				<div class="container">
					<a class="navbar-brand mr-4" href="{% url 'bank_app:view_profile' %}"
						>Bank home</a
					>
					<button
						class="navbar-toggler"
						type="button"
						data-toggle="collapse"
						data-target="#navbarToggle"
						aria-controls="navbarToggle"
						aria-expanded="false"
						aria-label="Toggle navigation"
					>
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarToggle">
						<div class="navbar-nav mr-auto">
							<a
								class="nav-item nav-link"
								href="{% url 'bank_app:view_profile' %}"
								>Profile</a
							>
							<a
								class="nav-item nav-link"
								href="{% url 'bank_app:view_my_accounts' %}"
								>My accounts</a
							>

							<!-- Default dropright button -->
							<div class="btn-group dropright">
								<button
									type="button"
									class="btn btn-secondary dropdown-toggle"
									data-toggle="dropdown"
									aria-haspopup="true"
									aria-expanded="false"
								>
									Select action
								</button>
								<div class="dropdown-menu">
									<!-- Dropdown menu links -->

									<a
										class="dropdown-item"
										href="{% url 'bank_app:form_transfer_money' %}"
										>Transfer money</a
									>

									<a
										class="dropdown-item"
										href="{% url 'bank_app:form_make_loan_payment' %}"
										>Loan payment</a
									>

									<a
										class="dropdown-item"
										href="{% url 'bank_app:form_take_a_loan' %}"
										>Take loan</a
									>
								</div>
							</div>
						</div>
						<!-- Navbar Right Side -->
						<div class="navbar-nav">
							<a class="nav-item nav-link" href="{% url 'login_app:logout' %}"
								>Log out ({{ user.first_name }} {{ user.last_name }})</a
							>
						</div>
					</div>
				</div>
			</nav>
		</header>

		<main role="main" class="container position-relative">
			<div class="notification-wrap"></div>
			<div class="row">
				<!-- message alerts -->
				{% for message in messages %}
				<div class="container-fluid p-0">
					<div class="alert {{ message.tags }} alert-dismissible" role="alert">
						<button
							type="button"
							class="close"
							data-dismiss="alert"
							aria-label="Close"
						>
							<span aria-hidden="true">&times;</span>
						</button>
						{{ message }}
					</div>
				</div>
				{% endfor %}

				<div class="col-md-12">{% block content %} {% endblock %}</div>
			</div>
		</main>

		{% block footer %} {% endblock %}

		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script
			src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
			integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
			crossorigin="anonymous"
		></script>
		<script
			src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
			integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
			crossorigin="anonymous"
		></script>
		<script
			src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
			integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
			crossorigin="anonymous"
		></script>
		<script>
			const socket = new WebSocket(
				"ws://" + window.location.host + "/ws/notifications"
			);

			// Socket On receive message Functionality
			socket.onmessage = function (e) {
				const element = `<div class="notification">
				<div id="close_notification"> x </div>
				<p>${e.data}</p>
				</div>`;
				document
					.querySelector(".notification-wrap")
					.insertAdjacentHTML("afterbegin", element);

				document.querySelectorAll("#close_notification").forEach((e, i) => {
					e.addEventListener("click", () => {
						e.parentElement.style.display = "none";
					});
				});
			};

			// Socket Connet Functionality
			socket.onopen = function (e) {
				console.log("open", e);
			};

			// Socket Error Functionality
			socket.onerror = function (e) {
				console.log("error", e);
			};

			// Socket close Functionality
			socket.onclose = function (e) {
				console.log("closed", e);
			};

			const socketTransfer = new WebSocket(
				"ws://" + window.location.host + "/ws/transferNotifications"
			);

			// SocketTransfer On receive message Functionality
			socketTransfer.onmessage = function (e) {
				const element = `<div class="notification">
				<div id="close_notification"> x </div>
				<p>${e.data}</p>
				</div>`;
				document
					.querySelector(".notification-wrap")
					.insertAdjacentHTML("afterbegin", element);

				document.querySelectorAll("#close_notification").forEach((e, i) => {
					e.addEventListener("click", () => {
						e.parentElement.style.display = "none";
					});
				});
			};

			// SocketTransfer Connet Functionality
			socketTransfer.onopen = function (e) {
				console.log("open", e);
			};

			// SocketTransfer Error Functionality
			socketTransfer.onerror = function (e) {
				console.log("error", e);
			};

			// SocketTransfer close Functionality
			socketTransfer.onclose = function (e) {
				console.log("closed", e);
			};
		</script>
	</body>
</html>

bank_app/templates/bank_app/create_user.html
{% extends "bank_app/base.html" %} {% block title %} index page {% endblock %}
{% block content %}
<h2> Create user: </h2>

<form action="{% url 'bank_app:create_user' %}" method="POST">
  {% csrf_token %}
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="user_name">User name</label>
      <input type="text" class="form-control" name="user_name"  id="user_name" placeholder="user name">
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="first_name">First name</label>
      <input type="text" class="form-control" name="first_name" id="first_name" placeholder="eg. John">
    </div>
    <div class="form-group col-md-6">
      <label for="last_name">Last name</label>
      <input type="text" class="form-control" name="last_name" id="last_name" placeholder="eg. Smith">
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="email">Email</label>
      <input type="email" class="form-control" name="email"  id="email" placeholder="eg. john@john.com">
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="phone_number">Phone number</label>
      <input type="tel" class="form-control" name="phone_number"  id="phone_number" placeholder="123456">
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-4">
      <label for="type">User type</label>
      <select name="type" id="type" class="form-control" >
        {% for type in user_types %}
        <option value={{type.id}}>{{type.text}}</option>
        {% endfor %}
      </select>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="password">Password</label>
      <input type="password" class="form-control" name="password" id="password" placeholder="password">
    </div>
    <div class="form-group col-md-6">
      <label for="confirm_password">Confirm password</label>
      <input type="password" class="form-control" name="confirm_password" id="confirm_password" placeholder="password">
    </div>
  </div>
  <button type="submit" class="btn btn-outline-secondary">Create user</button>
</form>
{% endblock %}

bank_app/templates/bank_app/form_make_loan_payment.html
{% extends "bank_app/base_customer.html" %} {% block content %}

<h1>Make loan payment</h1>

<form action="{% url 'bank_app:form_make_loan_payment' %}" method="POST">
	{% csrf_token %}
	<div class="input-group mb-3">
		<select
			class="custom-select"
			id="inputGroupSelect02"
			name="loan_account_number"
		>
			<option selected>Choose loan</option>
			{% for loan in loans %}
			<option value="{{loan.account_number}}">{{ loan.account_number }}</option>
			{% endfor %}
		</select>
		<div class="input-group-append">
			<label class="input-group-text" for="inputGroupSelect02">Options</label>
		</div>
	</div>

	<div class="input-group mb-3">
		<select
			class="custom-select"
			id="inputGroupSelect02"
			name="standard_account_number"
		>
			<option selected>Choose account to pay from</option>
			{% for account in accounts %}
			<option value="{{account.account_number}}">
				{{ account.account_number }}
			</option>
			{% endfor %}
		</select>
		<div class="input-group-append">
			<label class="input-group-text" for="inputGroupSelect02">Options</label>
		</div>
	</div>

	<div class="input-group mb-3">
		<input
			type="text"
			class="form-control"
			name="amount"
			placeholder="Enter amount to pay"
		/>
		<div class="input-group-append">
			<span class="input-group-text">DKK</span>
		</div>
	</div>

	<button class="btn btn-outline-secondary" type="submit">Make payment</button>
</form>

{% endblock %} {% block footer %} {% endblock %}

bank_app/templates/bank_app/form_take_a_loan.html
{% extends "bank_app/base_customer.html" %} {% block content %}

<h1>Take a loan</h1>

<form action="{% url 'bank_app:form_take_a_loan' %}" method="POST">
	{% csrf_token %}
	<div class="input-group mb-3">
		<select class="custom-select" id="inputGroupSelect02" name="account">
			<option selected>Choose account to receive money</option>
			{% for account in accounts %}
			<option value="{{account.account_number}}">
				{{ account.account_number }}
			</option>
			{% endfor %}
		</select>
		<div class="input-group-append">
			<label class="input-group-text" for="inputGroupSelect02">Options</label>
		</div>
	</div>

	<div class="input-group mb-3">
		<input
			type="text"
			class="form-control"
			name="amount"
			placeholder="How much money would you like to borrow?"
		/>

		<div class="input-group-apppend">
			<span class="input-group-text">DKK</span>
		</div>
	</div>
	<button class="btn btn-outline-secondary" type="submit">Take a loan</button>
</form>

{% endblock %} {% block footer %} {% endblock %}

bank_app/templates/bank_app/form_transfer_money.html
{% extends "bank_app/base_customer.html" %} {% block content %}

<h1>Transfer money</h1>

<form action="{% url 'bank_app:form_transfer_money' %}" method="POST">
	{% csrf_token %}
	<div class="input-group mb-3">
		<select
			class="custom-select"
			id="inputGroupSelect02"
			name="standard_account_number"
		>
			<option selected>Choose account to pay from</option>
			{% for account in accounts %}
			<option value="{{account.account_number }}">
				{{ account.account_number }}
			</option>
			{% endfor %}
		</select>
		<div class="input-group-append">
			<label class="input-group-text" for="inputGroupSelect02">Options</label>
		</div>
	</div>

	<div class="input-group mb-3">
		<input
			type="number"
			class="form-control"
			name="amount"
			min="0"
			step=".01"
		/>
		<div class="input-group-apppend">
			<span class="input-group-text">DKK</span>
		</div>
	</div>
	<div class="input-group mb-3">
		<input
			type="number"
			class="form-control col-2"
			name="bank_code"
			placeholder="code"
		/>
		<input
			type="account"
			class="form-control col-10"
			name="receiver_account_number"
			placeholder="Receiver account number"
		/>
	</div>
	<textarea
		class="form-control"
		rows="5"
		name="description"
		placeholder="Transaction description"
	></textarea>
	<button class="btn btn-outline-secondary" type="submit">
		Transfer money
	</button>
</form>

{% endblock %} {% block footer %} {% endblock %}