bank_app/urls.py
from django.urls import path, include
from . import views
from channels.routing import ProtocolTypeRouter, URLRouter, ChannelNameRouter
from .api import UserProfileDetail, UserProfileList, AccountsList, AccountsPerTypeList, TransactionsList, TransactionsPerAccountList


app_name = 'bank_app'

urlpatterns = [
    path('bank/view_accounts/', views.view_accounts, name='view_accounts'),
    path('bank/view_users/', views.view_users, name='view_users'),
    path('bank/view_users/<str:user_id>',
         views.user_details, name='user_details'),
    path('bank/create_user/', views.create_user, name='create_user'),
    path('bank/create_account/', views.create_account, name='create_account'),
    path('bank/user_types/', views.user_types, name='user_types'),
    path('bank/view_account_details/<str:account_id>',
         views.view_account_details, name='view_account_details'),
    path('bank/send_notification/',
         views.send_notification, name='send_notification'),
    path('bank/access_denied/', views.access_denied, name='access_denied'),
    path('bank/generate_pdf_with_account_details/<str:account_id>',
         views.generate_pdf_with_account_details, name='generate_pdf_with_account_details'),
    path('customer/view_profile/', views.view_profile, name='view_profile'),
    path('customer/user_view_account_details/<int:account_id>',
         views.user_view_account_details, name='user_view_account_details'),
    path('customer/form_make_loan_payment/', views.form_make_loan_payment,
         name='form_make_loan_payment'),
    path('customer/view_my_accounts/',
         views.view_my_accounts, name='view_my_accounts'),
    path('customer/form_take_a_loan/',
         views.form_take_a_loan, name='form_take_a_loan'),
    path('customer/form_transfer_money/', views.form_transfer_money,
         name='form_transfer_money'),
    path('customer/access_denied/', views.access_denied, name='access_denied'),
    path('api/v1/accounts/', AccountsList.as_view({'get': 'list'})),
    path('api/v1/accounts/<str:account_type>/',
         AccountsPerTypeList.as_view({'get': 'list'})),
    #path('api/v1/accounts/<int:account_id>/', AccountsList.as_view({'get':'retrieve'})),
    path('api/v1/transactions/', TransactionsList.as_view({'get': 'list'})),
    path('api/v1/transactions/<int:account_number>/',
         TransactionsPerAccountList.as_view({'get': 'list'})),
    path('api/v1/customers/<int:user_id>/',
         UserProfileDetail.as_view({'get': 'retrieve'})),
    path('api/v1/customers/<str:user_type_text>/',
         UserProfileList.as_view({'get': 'retrieve'})),
    path('api/v1/rest-auth/', include('rest_auth.urls')),

]

bank_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('bank_app/', include('bank_app.urls')),
    path('accounts/', include('login_app.urls')),
]

login_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views



app_name = 'login_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('password_reset_secret/<str:secret>',
         views.password_reset_secret, name='password_reset_secret'),
    path('password_reset_form/', views.password_reset_form,
         name='password_reset_form'),
    path('password_change/', views.password_change, name='password_change'),

    
]

login_app/models.py
from django.db import models
from django.contrib.auth.models import User
from secrets import token_urlsafe


class PasswordResetRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=43, default=token_urlsafe)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    updated_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user} - {self.created_timestamp} - {self.updated_timestamp} - {self.token}'

login_app/views.py
from django.shortcuts import render, reverse, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.http import HttpResponseRedirect
from . import models
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
import django_rq
from . messaging import email_message


def login(request):
    context = {}

    if request.method == "POST":
        user = authenticate(
            request, username=request.POST['user'], password=request.POST['password'])
        if user:
            if user.groups.filter(name='Clients').exists():
                dj_login(request, user)
                return HttpResponseRedirect(reverse('bank_app:view_profile'))
            elif user.groups.filter(name='Employees').exists():
                dj_login(request, user)
                return HttpResponseRedirect(reverse('bank_app:view_users'))
        else:
            context = {
                'error': 'Bad username or password.'
            }
    return render(request, 'login_app/login.html', context)


def logout(request):
    dj_logout(request)
    return render(request, 'login_app/login.html')


def password_reset(request):
    context = {}

    if request.method == "POST":
        email = request.POST['email']
        user = User.objects.get(email=email)
        reset_request = models.PasswordResetRequest()
        reset_request.user = user
        reset_request.save()
        url = reverse('login_app:password_reset_secret',
                      args=[f'{reset_request.token}'])
        url = f'{request.scheme}://{request.META["HTTP_HOST"]}{url}'
        print(url)
        context = {
            'message': 'Please click the link in the email we sent to you.'}
        django_rq.enqueue(email_message, {
            'reset-link': url,
            'email_reveiver': email,
        })
        return HttpResponseRedirect(reverse('login_app:password_reset'))

    return render(request, 'login_app/password_reset.html', context)


def password_reset_secret(request, secret):
    context = {'secret': secret}
    return render(request, 'login_app/new_password.html', context)


def password_reset_form(request):
    context = {}
    email = request.POST['email']
    token = request.POST['secret']
    password = request.POST['password']
    confirm_password = request.POST['confirm_password']

    user = User.objects.get(email=email)
    reset_request = models.PasswordResetRequest.objects.get(
        user=user, token=token)
    if password == confirm_password:
        user.set_password(password)
        user.save()
        reset_request.save()
    else:
        print("error")

    return render(request, 'login_app/new_password.html', context)


def password_change(request):

    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(
                request, 'Your password was successfully updated!')
            return redirect('bank_app:view_profile')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'login_app/change_password.html', {
        'form': form
    })

login_app/templates/login_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
		/>
		<meta http-equiv="X-UA-Compatible" content="ie=edge" />
		<!-- Bootstrap CSS -->
		<link
			rel="stylesheet"
			href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
			integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
			crossorigin="anonymous"
		/>
		<link
			rel="stylesheet"
			type="text/css"
			href="{% static 'bank_app/style.css' %}"
		/>

		<title>Bank</title>
	</head>
	<body>
		<header class="site-header">
			<nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
				<div class="container">
					<a class="navbar-brand mr-4" href="{% url 'bank_app:view_profile' %}"
						>Bank home</a
					>
				</div>
			</nav>
		</header>

		<main role="main" class="container">
			<div class="row">
				<!-- message alerts -->
				{% for message in messages %}
				<div class="container-fluid p-0">
					<div class="alert {{ message.tags }} alert-dismissible" role="alert">
						<button
							type="button"
							class="close"
							data-dismiss="alert"
							aria-label="Close"
						>
							<span aria-hidden="true">&times;</span>
						</button>
						{{ message }}
					</div>
				</div>
				{% endfor %}

				<div class="col-md-12">{% block content %} {% endblock %}</div>
			</div>
		</main>

		{% block footer %} {% endblock %}

		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script
			src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
			integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
			crossorigin="anonymous"
		></script>
		<script
			src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
			integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
			crossorigin="anonymous"
		></script>
		<script
			src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
			integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
			crossorigin="anonymous"
		></script>
	</body>
</html>

login_app/templates/login_app/change_password.html
{% extends "login_app/base.html" %} {% block title %} Login page {% endblock %}
{% block content %}
<form method="post">

  {% csrf_token %}
  {{ form.as_p }}
 
  <button class="btn btn-secondary" type="submit">Save changes</button>
  
</form>
{% endblock %}

login_app/templates/login_app/login.html
{% extends "login_app/base.html" %} {% block title %} Login page {% endblock %}
{% block content %}

    <h1>Login</h1>
     <hr />
    <form action="{% url 'login_app:login' %}" method="POST">
      {% csrf_token %}
       <div class="form-row">
        <div class="form-group col-md-6">
          <input type="text" name="user" placeholder="User Name" class="form-control" />
        </div>
      </div>
       <div class="form-row">
        <div class="form-group col-md-6">
          <input type="password" name="password" placeholder="Password" class="form-control" />
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <button  class="btn btn-secondary">Login</button>
        </div>
      </div>
    </form>
      <a href="{% url 'login_app:password_reset' %}">Reset password</a>
    <hr />
    {% if error %} {{ error }} {% endif %}
  </body>
</html>
     {% endblock %}      

login_app/templates/login_app/new_password.html
{% extends "login_app/base.html" %} {% block title %} index page {% endblock %}
{% block content %}
<h1>New password</h1>
<a href="{% url 'login_app:login' %}">Login</a>

<hr />
<form action="{% url 'login_app:password_reset_form' %}" method="POST">
  {% csrf_token %}
  <div class="form-row">
    <div class="form-group col-md-6">
      <input type="hidden" name="secret" value="{{ secret }}" />
      <input
        type="email"
        name="email"
        placeholder="Email"
        class="form-control"
      />
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <input
        type="password"
        name="password"
        placeholder="Password"
        class="form-control"
      />
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <input
        type="password"
        name="confirm_password"
        placeholder="Confirm Password"
        class="form-control"
      />
    </div>
  </div>
  <button class="btn btn-secondary">Save</button>
</form>
{% endblock %}

login_app/templates/login_app/password_change1.html
{% extends "login_app/base.html" %} {% block title %} index page {% endblock %}
{% block content %}

    <h1>Login</h1>
     <hr />
    <form action="{% url 'login_app:password_change' %}" method="POST">
      {% csrf_token %}

             <div class="form-row">
        <div class="form-group col-md-6">
          <input type="password" name="current_password" placeholder="Current password" class="form-control" />
        </div>
      </div>
       <div class="form-row">
        <div class="form-group col-md-6">
          <input type="password" name="new_password" placeholder="New password" class="form-control" />
        </div>
      </div>
             <div class="form-row">
        <div class="form-group col-md-6">
          <input type="password" name="new_password" placeholder="Repeat new password" class="form-control" />
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <button  class="btn btn-secondary">Save</button>
        </div>
      </div>
    </form>
      <a href="{% url 'login_app:password_reset' %}">Reset password</a>
    <hr />
    {% if error %} {{ error }} {% endif %}
  </body>
</html>
{% endblock %}

login_app/templates/login_app/password_reset.html
{% extends "login_app/base.html" %} {% block title %} index page {% endblock %}
{% block content %}
<h1>Password reset</h1>
<a href="{% url 'login_app:login' %}">login</a>

<hr />
<form action="{% url 'login_app:password_reset' %}" method="POST">
  {% csrf_token %}
  <div class="form-row">
    <div class="form-group col-md-6">
      <input
        type="email"
        name="email"
        placeholder="Email Address"
        class="form-control"
      />
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <button class="btn btn-secondary">Submit</button>
    </div>
  </div>
</form>
<hr />
{% endblock %}